const jokes = [
  "To whoever stole my copy of Microsoft Office, I will find you. You have my Word!",
  "To the guy who invented zero, thanks for nothing!",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "I used to play piano by ear, but now I use my hands and fingers.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I only know 25 letters of the alphabet. I don't know y.",
  "Did you hear about the mathematician who’s afraid of negative numbers? He'll stop at nothing to avoid them.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I used to be a baker because I kneaded dough.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I only know 3 jokes. The rest are true stories.",
  "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands and fingers.",
  "What did the grape say when it got stepped on? Nothing, but it let out a little wine.",
  "Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field!",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I used to be a baker because I kneaded dough.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
  "I only know 3 jokes. The rest are true stories.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What did one hat say to the other? Stay here, I'm going on ahead!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "I used to play piano by ear, but now I use my hands and fingers.",
  "What's a vampire's favorite fruit? A blood orange.",
  "Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field!",
  "Why did the coffee file a police report? It got mugged.",
  "What did one plate say to another? Tonight, dinner's on me!",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
  "I only know 3 jokes. The rest are true stories.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What did one hat say to the other? Stay here, I'm going on ahead!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "I used to play piano by ear, but now I use my hands and fingers.",
  "What's a vampire's favorite fruit? A blood orange.",
  "Why did the scarecrow become a successful neurosurgeon? Because he was outstanding in his field!",
  "Why did the coffee file a police report? It got mugged.",
  "What did one plate say to another? Tonight, dinner's on me!",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Did you hear about the cheese factory explosion? There was nothing left but de-brie.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "Parallel lines have so much in common. It’s a shame they’ll never meet.",
  "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
  "I only know 3 jokes. The rest are true stories.",
  "Why did the bicycle fall"
]

let randomNumber = Math.floor(Math.random() * (jokes.length));
let a=document.getElementById("joke")
a.innerHTML=jokes[randomNumber]
const reload=()=>{
  location.reload();
}
